FROM localhost/base AS ctngbuild

ARG DEBIAN_FRONTEND="noninteractive"
LABEL description="Temporary image to compile crosstool-ng"
ENV TZ="America/Sao_Paulo"
ARG CTNG_UID=1000
ARG CTNG_GID=1000

RUN apt update \
  && apt install -y -f autoconf \
    automake \
    bison \
    flex \
    gperf \
    help2man \
    python3-dev \
    texinfo \
    libtool \
    libtool-bin \
    libstdc++6 \
  && rm -rf /var/lib/apt/lists/* \
  && groupadd -g $CTNG_GID ctng \
  && useradd -d /home/ctng -m -g $CTNG_GID -u $CTNG_UID -s /bin/bash ctng \
  && mkdir /opt/ctng \
  && chmod 777 /opt/ctng \
  && mkdir /opt/x-tools \
  && chmod 777 /opt/x-tools \
  && echo 'export PATH=/opt/ctng/bin:$PATH' >> /etc/profile
  
USER ctng

RUN wget -O /tmp/crosstool.bz2 http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.bz2 \
  && cd /home/ctng \
  && tar xvf /tmp/crosstool.bz2 \
  && rm /tmp/crosstool.bz2 \
  && cd /home/ctng/crosstool-ng-1.25.0 \
  && ./configure --prefix=/opt/ctng \
  && make \
  && make install \
  && echo 'CT_CONFIG_VERSION="4"' >> /tmp/defconfig \
  && echo 'CT_PREFIX_DIR="/opt/x-tools/${CT_HOST:+HOST-${CT_HOST}/}${CT_TARGET}"' >> /tmp/defconfig \
  && echo 'CT_ARCH_CPU="cortex-a53"' >> /tmp/defconfig \
  # && echo 'CT_ARCH_SUFFIX="v8"' >> /tmp/defconfig \
  # && echo 'CT_ARCH_FPU="neon"' >> /tmp/defconfig \
  && echo 'CT_ARCH_ARM=y' >> /tmp/defconfig \
  && echo 'CT_ARCH_64=y' >> /tmp/defconfig \
  && echo 'CT_TARGET_VENDOR="trimui"' >> /tmp/defconfig \
  # && echo 'CT_OMIT_TARGET_VENDOR=y' >> /tmp/defconfig \
  && echo 'CT_ARCH_FLOAT_HW=n' >> /tmp/defconfig \
  && echo 'CT_KERNEL_LINUX=y' >> /tmp/defconfig \
  && echo 'CT_LINUX_V_4_9=y' >> /tmp/defconfig \
  && echo 'CT_BINUTILS_V_2_32=y' >> /tmp/defconfig \
  && echo 'CT_BINUTILS_LINKER_LD_GOLD=y' >> /tmp/defconfig \
  && echo 'CT_BINUTILS_GOLD_THREADS=y' >> /tmp/defconfig \
  && echo 'CT_BINUTILS_LD_WRAPPER=y' >> /tmp/defconfig \
  && echo 'CT_BINUTILS_PLUGINS=y' >> /tmp/defconfig \
  && echo 'CT_GLIBC_V_2_23=y' >> /tmp/defconfig \
  && echo 'CT_GCC_V_9=y' >> /tmp/defconfig \
  && echo 'CT_CC_LANG_CXX=y' >> /tmp/defconfig \
  && echo 'CT_CC_GCC_LIBGOMP=y' >> /tmp/defconfig \
  && cd /tmp \
  && /opt/ctng/bin/ct-ng defconfig \
  && echo 'CT_ZLIB_MIRRORS="http://downloads.sourceforge.net/project/libpng/zlib/${CT_ZLIB_VERSION} https://www.zlib.net/ https://www.zlib.net/fossils"' >> /tmp/.config \
  && /opt/ctng/bin/ct-ng build \
  && rm -rf /opt/ctng/* \
  && rm -rf /tmp/*
